ut dod enslig auto brev
navikt/pensjonsbrev pull request #12
Opened 2022-01-10 15:09 UTC by hconhegg

Partially finished letter. Merging to not deviate too much from master feature set.

2022-01-11 12:50 UTC, routsi requested changes

2022-01-11 12:50 UTC, routsi commented on docker-compose.yml
> +#      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 #opens up debug port
Du kan gjerne "kommentere" debug linjen inn igjen. Ikke noe problem å debugging være aktiv :)

2022-01-11 12:50 UTC, routsi commented on pensjon-brevbaker-api-model/build.gradle.kts
>  group = "no.nav.pensjon.brev"
Om du skiller api-model endringene ut i en egen PR så kan vi få grønt bygg før vi merger brevbaker endringene.

2022-01-11 12:50 UTC, routsi commented on pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/api/TemplateResource.kt
> +        UfoerOmregningEnslig
Burde kanskje ikke publisere det uferdige brevet?

2022-01-11 12:50 UTC, routsi commented on pensjon-brevbaker/build.gradle.kts
> +    implementation("io.ktor:ktor-auth:$ktor_version")
Ser ut til at du har lagt til duplikater av ktor-auth avhengighetene?

2022-01-11 12:50 UTC, routsi commented on pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/LetterTemplate.kt
> +data class AttachmentTemplate<ParameterType : Any>(
Lurer litt på om vi skal flytte denne over i IncludeAttachment.kt?

2022-01-11 12:50 UTC, routsi commented on pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/base/PensjonLatex.kt
> +            val scope = with(letter.toScope()) {
Innser nå at det nok leser bedre med:
```
val scope = letter.toScope().let {
   ExpressionScope(attachment.data.eval(it), it.felles, it.language)
}
```

2022-01-11 12:50 UTC, routsi commented on pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/base/PensjonLatex.kt
> +                if (items.isNotEmpty() && items.any{it.isNotBlank()}){
Burde ikke være nødvendig å sjekke om listen har elementer. any svarer false om den er tom. p.s. det mangler noen mellomrom.

2022-01-11 12:50 UTC, routsi commented on pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/base/PensjonLatex.kt
> +                        printWriter.printCmd("begin") {
Når du er i scopet til `with(printWriter)` så vil funksjonene til LatexPrintWriter være direkte tilgjengelig, så du trenger ikke å skrive `printWriter.` først.

2022-01-11 12:50 UTC, routsi commented on pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/dsl/Expression.kt
> +fun <T:Enum<T>> Expression<Enum<T>>.isOneOf(vararg enums: Enum<T>):Expression<Boolean>
Mangler noen mellomrom her

2022-01-12 08:51 UTC, hconhegg commented on pensjon-brevbaker-api-model/build.gradle.kts
>  group = "no.nav.pensjon.brev"
https://github.com/navikt/pensjonsbrev/pull/13

2022-01-12 09:33 UTC, routsi approved these changes

2022-01-12 09:35 UTC, merged