Flyttet/gjenskapt valg av brevmal/e-blankett
navikt/pensjonsbrev pull request #331
Opened 2023-11-22 13:56 UTC by johannbm

Ikke alt er på plass, men har henting av data og strukturen på det å velge et brev.

Kan testes ut her https://pensjon-skribenten-web.intern.dev.nav.no/

2023-11-22 14:27 UTC, johannbm commented on skribenten-web/bff/.nais/bff-dev.yaml
> +    - "https://pensjon-skribenten-web.ekstern.dev.nav.no"
Gjorde den midlertidig ekstern i dev slik at Karoline enkelt kan teste

2023-11-23 09:25 UTC, hconhegg requested changes

2023-11-23 09:25 UTC, hconhegg commented on skribenten-web/bff/.nais/bff-dev.yaml
> +    - "https://pensjon-skribenten-web.ekstern.dev.nav.no"
🙅🙅🙅

2023-11-23 09:25 UTC, hconhegg commented on skribenten-web/frontend/src/types/apiTypes.ts
> +// TODO: verify typo in EXTERAM?
Produktet heter HP EXTREAM. 🤣 Typos var kult i 2003.

2023-11-23 09:25 UTC, hconhegg commented on skribenten-web/frontend/src/types/apiTypes.ts
> +  Extream = "EXTERAM",
EXTREAM er riktig.  Kunne du tatt en word replace i hele skribenten/frontend på EXTERAM -> EXTREAM? I dun goofd :sweat:

2023-11-23 09:26 UTC, hconhegg commented on skribenten-web/bff/.nais/bff-dev.yaml
> +    - "https://pensjon-skribenten-web.ekstern.dev.nav.no"
Risk/reward går ikke opp her når vi integrerer mot andre systemer som kan ha problemer ved eksponering.

2023-11-24 08:57 UTC, hconhegg commented on skribenten-web/frontend/src/types/apiTypes.ts
> +  Frank = "FR",
Fransk*

2023-11-24 08:57 UTC, hconhegg commented on skribenten-web/frontend/src/types/apiTypes.ts
> +  Frank = "FR",
Usikker på om vi faktisk har nordsamisk og fransk. Tror det var forsøkt på ett brev elns.

2023-11-24 08:58 UTC, hconhegg approved these changes

2023-11-24 16:09 UTC, merged