Legger til restanse i revurderingsmal oms
navikt/pensjonsbrev pull request #658
Opened 2024-03-13 15:40 UTC by Bjodn

2024-03-13 20:45 UTC, henrikg approved these changes
Sjekk opp dette ift når restanse er lik mellom to vurderinger - da har den ikke blitt økt eller redusert.

2024-03-13 20:45 UTC, henrikg commented on pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/omstillingsstoenad/BeregningAvOmstillingsstoenad.kt
> +	                Nynorsk to "",
Det er lagt inn nynorsk og engelsk også ser det ut til

2024-03-13 20:45 UTC, henrikg commented on pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/omstillingsstoenad/BeregningAvOmstillingsstoenad.kt
> +		            Bokmal to "Siden den forventede inntekten din er ".expr() + ifElse(inntektHarOkt, "økt", "redusert") +
Hvordan blir dette hvis man har en revurdering av noe helt annet enn inntekt og restanse allerede er x kroner. Da vil den her fortsatt være x , og avsnittet burde vel fortsatt stå der, men med en litt annen tekst? eller?

2024-03-13 20:45 UTC, henrikg commented on pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/omstillingsstoenad/BeregningAvOmstillingsstoenad.kt
> +                            " enn det som fremgår i tabellen over, under “Utbetaling per måned”",
Lurer på om det burde stå `«Utbetaling per måned»` da de tegnene der er brukt på andre henvisninger såvidt jeg vet.

2024-03-19 14:33 UTC, henrikg approved these changes

2024-03-19 20:17 UTC, henrikg approved these changes

2024-03-20 07:48 UTC, Watercolours approved these changes

2024-03-20 08:03 UTC, hconhegg commented
Bruk heller .absoluteValue(). Vi har med vilje utelatt gange dele osv for å ikke ha business logikk i malene.

2024-03-20 08:03 UTC, hconhegg requested changes
Bruk heller .absoluteValue(). Vi har med vilje utelatt gange dele osv for å ikke ha business logikk i malene.

2024-03-20 08:10 UTC, hconhegg approved these changes

2024-03-20 08:41 UTC, merged