Feature/pl 6066
navikt/pensjonsbrev pull request #96
Opened 2022-11-04 09:17 UTC by e136581

2022-11-04 14:07 UTC, hconhegg commented on pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/omregning/ufoeretrygd/Ufoeretrygd.kt
> +            paragraph {
Does this text belong here in this phrase? if so, can you include the old reference to this text in the comment above ?     TBU3008, TBU3009, TBU3010, ???

2022-11-04 14:09 UTC, hconhegg commented on pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/vedlegg/OrienteringOmRettigheterAlder.kt
> +                    harTilleggForFlereBarn = harTilleggForFlereBarn
No need for the first part of harTilleggForFlereBarn = harTilleggForFlereBarn. You can also put this includephrase on one line.

2022-11-04 14:09 UTC, hconhegg commented on pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/vedlegg/OrienteringOmRettigheterAlder.kt
> +            includePhrase(
Put all the includephrase on one line

2022-11-04 14:09 UTC, hconhegg commented on pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/vedlegg/OrienteringOmRettigheterAlder.kt
> +                    bruker_sivilstand,
Put all the includephrase on one line

2022-11-04 14:13 UTC, hconhegg requested changes
Some refactoring is needed.

2022-11-04 14:40 UTC, e136581 commented on pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/vedlegg/OrienteringOmRettigheterAlder.kt
> +                    bruker_sivilstand,
Corrected and pushed

2022-11-07 08:46 UTC, hconhegg approved these changes

2022-11-07 11:21 UTC, merged